import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1790253677580 implements MigrationInterface {
    name = 'InitialSchema1790253677580'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" character varying NOT NULL, "email" character varying NOT NULL, "passwordHash" character varying, "name" character varying NOT NULL DEFAULT 'Guest User', "phone" character varying, "avatarUrl" character varying, "role" character varying NOT NULL DEFAULT 'user', "city" character varying NOT NULL DEFAULT 'Hyderabad', "rewardPoints" integer NOT NULL DEFAULT '1250', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "theatres" ("id" character varying NOT NULL, "name" character varying NOT NULL, "location" character varying NOT NULL, "distance" character varying NOT NULL, "amenities" text NOT NULL, "showtimes" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a1451caeaf6c1085e17e01ffe4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sports_venues" ("id" character varying NOT NULL, "name" character varying NOT NULL, "supportedSports" text NOT NULL, "coverImageUrl" character varying NOT NULL, "galleryImages" text NOT NULL, "rating" double precision NOT NULL, "reviewCount" integer NOT NULL, "location" character varying NOT NULL, "distance" character varying NOT NULL, "amenities" text NOT NULL, "rules" text NOT NULL, "startingPricePerHour" double precision NOT NULL, "slots" jsonb, "addOns" jsonb, "isTrending" boolean NOT NULL DEFAULT false, "isPopular" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7700a615a0ae4a92103f0cc1bd3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rewards" ("id" character varying NOT NULL, "title" character varying NOT NULL, "partnerName" character varying NOT NULL, "pointsCost" integer NOT NULL, "discountValue" character varying NOT NULL, "category" character varying NOT NULL, "code" character varying NOT NULL, "expiryDate" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3d947441a48debeb9b7366f8b8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "restaurants" ("id" character varying NOT NULL, "name" character varying NOT NULL, "tagline" character varying NOT NULL, "about" text NOT NULL, "coverImageUrl" character varying NOT NULL, "galleryImages" text NOT NULL, "rating" double precision NOT NULL, "reviewCount" integer NOT NULL, "cuisines" text NOT NULL, "priceForTwo" double precision NOT NULL, "location" character varying NOT NULL, "distance" character varying NOT NULL, "openingHours" character varying NOT NULL, "isPureVeg" boolean NOT NULL DEFAULT false, "hasOutdoor" boolean NOT NULL DEFAULT false, "isOpenNow" boolean NOT NULL DEFAULT true, "offerBadge" character varying, "amenities" text NOT NULL, "popularDishes" jsonb, "reviews" jsonb, "availableSlots" jsonb, "isTrending" boolean NOT NULL DEFAULT false, "isFineDining" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e2133a72eb1cc8f588f7b503e68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" character varying NOT NULL, "name" character varying NOT NULL, "brand" character varying NOT NULL, "category" character varying NOT NULL, "price" double precision NOT NULL, "originalPrice" double precision, "rating" double precision NOT NULL, "reviewCount" integer NOT NULL, "coverImageUrl" character varying NOT NULL, "galleryImages" text NOT NULL, "description" text NOT NULL, "specifications" jsonb, "variants" jsonb, "storeId" character varying NOT NULL, "storeName" character varying NOT NULL, "storeLocation" character varying NOT NULL, "distance" character varying NOT NULL, "isTrending" boolean NOT NULL DEFAULT false, "isDealOfTheDay" boolean NOT NULL DEFAULT false, "discountBadge" character varying, "inStock" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plans" ("id" character varying NOT NULL, "userId" character varying NOT NULL DEFAULT 'user_default', "title" character varying NOT NULL, "date" character varying NOT NULL, "totalEstimatedCost" double precision NOT NULL, "totalDurationHours" integer NOT NULL, "slots" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" character varying NOT NULL, "userId" character varying NOT NULL DEFAULT 'user_default', "title" character varying NOT NULL, "message" text NOT NULL, "type" character varying NOT NULL, "timeAgo" character varying NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "actionRoute" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "movies" ("id" character varying NOT NULL, "title" character varying NOT NULL, "tagline" character varying, "synopsis" text NOT NULL, "posterUrl" character varying NOT NULL, "backdropUrl" character varying NOT NULL, "rating" double precision NOT NULL, "votesCount" integer NOT NULL, "genres" text NOT NULL, "duration" character varying NOT NULL, "primaryLanguage" character varying NOT NULL, "availableLanguages" text NOT NULL, "formats" text NOT NULL, "certificate" character varying NOT NULL, "releaseDate" character varying NOT NULL, "startingPrice" double precision NOT NULL, "trailerYoutubeId" character varying, "director" character varying NOT NULL, "cast" jsonb, "isNowShowing" boolean NOT NULL DEFAULT true, "isTrending" boolean NOT NULL DEFAULT false, "isComingSoon" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c5b2c134e871bfd1c2fe7cc3705" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hotels" ("id" character varying NOT NULL, "name" character varying NOT NULL, "tagline" character varying NOT NULL, "category" character varying NOT NULL, "startingPricePerNight" double precision NOT NULL, "originalPricePerNight" double precision, "rating" double precision NOT NULL, "reviewCount" integer NOT NULL, "coverImageUrl" character varying NOT NULL, "galleryImages" text NOT NULL, "description" text NOT NULL, "location" character varying NOT NULL, "distance" character varying NOT NULL, "amenities" text NOT NULL, "rooms" jsonb, "addOns" jsonb, "isTrending" boolean NOT NULL DEFAULT false, "isFeatured" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2bb06797684115a1ba7c705fc7b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "events" ("id" character varying NOT NULL, "title" character varying NOT NULL, "tagline" character varying NOT NULL, "description" text NOT NULL, "category" character varying NOT NULL, "posterUrl" character varying NOT NULL, "bannerUrl" character varying NOT NULL, "eventDate" character varying NOT NULL, "time" character varying NOT NULL, "venue" character varying NOT NULL, "location" character varying NOT NULL, "distance" character varying NOT NULL, "rating" double precision NOT NULL, "interestedCount" integer NOT NULL, "ageRestriction" character varying NOT NULL, "languages" character varying NOT NULL DEFAULT 'English & Telugu', "ticketTiers" jsonb, "performers" jsonb, "isTrending" boolean NOT NULL DEFAULT false, "isFeatured" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" character varying NOT NULL, "userId" character varying NOT NULL DEFAULT 'user_default', "type" character varying NOT NULL, "title" character varying NOT NULL, "subtitle" character varying NOT NULL, "imageUrl" character varying NOT NULL, "date" character varying NOT NULL, "time" character varying, "location" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'upcoming', "totalPrice" double precision NOT NULL, "qrCodeData" character varying NOT NULL DEFAULT 'CONFIRMED', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activities" ("id" character varying NOT NULL, "title" character varying NOT NULL, "tagline" character varying NOT NULL, "description" text NOT NULL, "category" character varying NOT NULL, "coverImageUrl" character varying NOT NULL, "galleryImages" text NOT NULL, "rating" double precision NOT NULL, "reviewCount" integer NOT NULL, "location" character varying NOT NULL, "distance" character varying NOT NULL, "highlights" text NOT NULL, "safetyGuidelines" text NOT NULL, "packages" jsonb, "addOns" jsonb, "timeSlots" jsonb, "isTrending" boolean NOT NULL DEFAULT false, "isPopular" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f4004429f731ffb9c88eb486a8" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "activities"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TABLE "events"`);
        await queryRunner.query(`DROP TABLE "hotels"`);
        await queryRunner.query(`DROP TABLE "movies"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "restaurants"`);
        await queryRunner.query(`DROP TABLE "rewards"`);
        await queryRunner.query(`DROP TABLE "sports_venues"`);
        await queryRunner.query(`DROP TABLE "theatres"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
